version: 2.1
# Use a package of configuration called an orb.
# orbs:
# Choose either one of the orbs below
# welcome: circleci/welcome-orb@0.4.1
# aws-cli: circleci/aws-cli@2.0.3

executors:
  aws_cli_executor:
    docker:
      - image: amazon/aws-cli
  python_alpine_executor:
    docker:
      - image: python:3.7-alpine3.11

# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
    executor: aws_cli_executor
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file infrastructure/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  # Exercise: Config and Deployment
  configure_infrastructure:
    executor: python_alpine_executor
    steps:
      - checkout
      # - add_ssh_keys:
      #     # You can get this ID in the section where you registered the SSH Key
      #     fingerprints: ["fd:cd:84:87:be:c3:48:6c:30:7e:31:23:bf:02:6f:1a"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
