---
- name: "update apt packages."
  become: true
  apt:
    update_cache: true

- name: "upgrade packages"
  become: true
  apt:
    upgrade: true

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true

- name: "install dependencies"
  become: true
  apt:
    name: ["nodejs", npm]
    state: latest
    update_cache: true

- name: "install pm2"
  become: true
  shell: |
    npm install pm2 -g

- name: "create directory"
  file:
    path: ~/web
    state: directory

- name: "copy index.js"
  copy:
    src: index.js
    dest: ~/web/index.js

- name: "start server"
  shell: |
    pm2 start ~/web/index.js -f

# ---
# - name: "update apt packages."
#   become: true
#   apt:
#     update_cache: true

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: true

# - name: remove dependencies that are no longer required
#   become: true
#   apt:
#     autoremove: true

# - name: "install dependencies"
#   become: true
#   shell: |
#     sudo curl https://nodejs.org/dist/v14.17.2/node-v14.17.2.tar.gz
#     sudo tar -xzf node-v0.x.x.tar.gz
#     cd node-v0.x.x.tar.gz
#     ./configure
#     sudo make install

# - name: "install build-essential"
#   become: true
#   apt:
#     name: build-essential
#     state: latest
#     update_cache: true

# - name: "create directory"
#   file:
#     path: ~/web
#     state: directory

# - name: "copy index.js"
#   copy:
#     src: index.js
#     dest: ~/web/index.js

# - name: "start server"
#   shell: |
#     node ~/web/index.js

